### ISSUE TITLE
Doesnt compile on ubuntu. Is this only for arch?

### ISSUE THREAD

**Issue by gwgw99** [InitializeSahib/KernelPanic#1] opened 2016-07-17 18:43 UTC
I don't have the arch/x86/entry/syscalls/syscall_32.tbl file, so I cant compile it. Should i have that? Heres the output of sudo make if that helps:
`gradyn@gradyns-desktop:~/Documents/KernelPanic-master$ sudo make 
make -C /lib/modules/4.4.0-24-generic/build M= modules
make[1]: Entering directory '/usr/src/linux-headers-4.4.0-24-generic'
make[2]: *** No rule to make target 'arch/x86/entry/syscalls/syscall_32.tbl', needed by 'arch/x86/entry/syscalls/../../include/generated/asm/syscalls_32.h'.  Stop.
arch/x86/Makefile:199: recipe for target 'archheaders' failed
make[1]: *** [archheaders] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.4.0-24-generic'
Makefile:3: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by InitializeSahib** [comment] 2016-07-18 01:52
Compiles perfectly on Ubuntu 15.10 amd64. Closing due to inability to reproduce.

**Closed by InitializeSahib** 2016-07-18 01:52 UTC
Labels: wontfix
